#!/usr/bin/env node
var mdeps = require('./');
var argv = require('minimist')(process.argv.slice(2));
var JSONStream = require('JSONStream');
var stringify = JSONStream.stringify();
var path = require('path');
var files = argv._.map(function (file) {return path.resolve(file)});
var deps = mdeps(files, argv);

deps.on('error', function(err) {
  console.error(err);
  process.exit(1);
});

deps.pipe(stringify).pipe(process.stdout);
